// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpaoMPCk-W0D2DhPRb7LihffJE6BFl4GA',
    appId: '1:732960090044:web:3ac3459a54652f80aaedb9',
    messagingSenderId: '732960090044',
    projectId: 'wuxia-6a4d2',
    authDomain: 'wuxia-6a4d2.firebaseapp.com',
    storageBucket: 'wuxia-6a4d2.firebasestorage.app',
    measurementId: 'G-ML2X6PXHBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlGEM1Yy0Q5BjXOW3-zlKS_CotQ0-VBUI',
    appId: '1:732960090044:android:f71fe85349c19bcaaaedb9',
    messagingSenderId: '732960090044',
    projectId: 'wuxia-6a4d2',
    storageBucket: 'wuxia-6a4d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB_B8azDIA4kiKFYRFm3DJP9O6DghMHRQ',
    appId: '1:732960090044:ios:117723c1be5228dbaaedb9',
    messagingSenderId: '732960090044',
    projectId: 'wuxia-6a4d2',
    storageBucket: 'wuxia-6a4d2.firebasestorage.app',
    iosBundleId: 'com.hubble.wuxia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB_B8azDIA4kiKFYRFm3DJP9O6DghMHRQ',
    appId: '1:732960090044:ios:46078b2d00b0040faaedb9',
    messagingSenderId: '732960090044',
    projectId: 'wuxia-6a4d2',
    storageBucket: 'wuxia-6a4d2.firebasestorage.app',
    iosBundleId: 'com.hubble.wuxia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpaoMPCk-W0D2DhPRb7LihffJE6BFl4GA',
    appId: '1:732960090044:web:75adb686649201acaaedb9',
    messagingSenderId: '732960090044',
    projectId: 'wuxia-6a4d2',
    authDomain: 'wuxia-6a4d2.firebaseapp.com',
    storageBucket: 'wuxia-6a4d2.firebasestorage.app',
    measurementId: 'G-V59SN26VK2',
  );
}
