// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0QPbt-1r1hUXoZpk_lVnfYzPwMi2wdCE',
    appId: '1:337040486387:web:0d25710d4c179f1d906c86',
    messagingSenderId: '337040486387',
    projectId: 'rumgap',
    authDomain: 'rumgap.firebaseapp.com',
    storageBucket: 'rumgap.appspot.com',
    measurementId: 'G-3Y81LRL9XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxkRM_TYLI1SSCurG7hCdr3EJC4vpwFd8',
    appId: '1:337040486387:android:bb59c6fccc7bf6f4906c86',
    messagingSenderId: '337040486387',
    projectId: 'rumgap',
    storageBucket: 'rumgap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAlAEtLrNzo544Ze-6gBQWNHSUvlZMVSk',
    appId: '1:337040486387:ios:ac70337d210151dd906c86',
    messagingSenderId: '337040486387',
    projectId: 'rumgap',
    storageBucket: 'rumgap.appspot.com',
    iosClientId: '337040486387-ec3mu91jkrdm4s3h8hm9kja3rul16j3t.apps.googleusercontent.com',
    iosBundleId: 'com.hubble.wuxia',
  );
}
